//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;

    public partial class EuroEntities : DbContext
    {
        public EuroEntities()
            : base("name=EuroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EuropeSery> EuropeSeries { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LCity> LCities { get; set; }
        public virtual DbSet<LCountry> LCountries { get; set; }
        public virtual DbSet<LText> LTexts { get; set; }
        public virtual DbSet<OldSery> OldSeries { get; set; }
        public virtual DbSet<Printery> Printeries { get; set; }
        public virtual DbSet<Text> Texts { get; set; }
    }
}
